### ISSUE TITLE
Increase timeout limit

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ZoteroImport#10]
```
2016-11-14T18:39:44+00:00 ERR (3): Zend\Http\Client\Adapter\Exception\TimeoutException: Read timed out after 10 seconds in /var/www/html/omeka-s/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php:600
Stack trace:
#0 /var/www/html/omeka-s/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php(412): Zend\Http\Client\Adapter\Socket->_checkSocketReadTimeout()
#1 /var/www/html/omeka-s/vendor/zendframework/zend-http/src/Client.php(1389): Zend\Http\Client\Adapter\Socket->read()
#2 /var/www/html/omeka-s/vendor/zendframework/zend-http/src/Client.php(893): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '')
#3 /var/www/html/omeka-s/modules/ZoteroImport/src/Job/Import.php(211): Zend\Http\Client->send()
#4 /var/www/html/omeka-s/modules/ZoteroImport/src/Job/Import.php(138): ZoteroImport\Job\Import->getResponse('https://api.zot...')
#5 /var/www/html/omeka-s/application/src/Job/Strategy/SynchronousStrategy.php(37): ZoteroImport\Job\Import->perform()
#6 /var/www/html/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\Strategy\SynchronousStrategy->send(Object(Omeka\Entity\Job))
#7 /var/www/html/omeka-s/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\Strategy\SynchronousStrategy))
#8 {main}
```

**Comment by jimsafley** [comment]
Fixed in 63ed47b0c220ad83ec4faff1b55d7e7601f495d0
