### ISSUE TITLE
Test ZoteroImport

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ZoteroImport#7]
@mebrett 

Not much has changed since you last tried this out, but it has been a long time. It should work as before.

**Comment by mebrett** [comment]
@omeka-s-modules/testing

**Comment by alyssafahringer** [comment]
Quick question: is import into a required field? It says in the helper text that it is, but the documentation doesn't, and there is no red asterisk next to it.

**Comment by jimsafley** [comment]
Pull in the newest changes. You should see the asterisk. The docs need to be updated to reflect this.

**Comment by alyssafahringer** [comment]
Asterisk there and documentation updated.

**Comment by alyssafahringer** [comment]
I think we should add to the documentation or to the helper text a blurb that reminds users that their Zotero library has to be published in order for the module to import, and that they have to manually remove any items they imported if they wish to do so (they can't go into the module and remove entire imports, as they can in API importer or something similar).

**Comment by alyssafahringer** [comment]
Imported Zotero library successfully.

**Comment by jimsafley** [comment]
@mebrett I've added an "undo import" feature that needs testing. You'll need to pull from master and reinstall the module. Once the import is complete you'll see an undo icon next to the import. Try it out. I made a few other changes under the hood, so I also need you to test the module generally. Thanks.

**Comment by jimsafley** [comment]
@mebrett I've yet again made some changes under the hood that will require more general testing of this module. Please thoroughly test the import and, most importantly, the undo import features. Thank you.

**Comment by mebrett** [comment]
I updated the module and tried to run an import. Got the following error after hitting submit:

```
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null' in /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#3 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1018): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(249): Doctrine\ORM\EntityManager->flush()
#7 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(215): Omeka\Api\Adapter\AbstractEntityAdapter->create(Object(Omeka\Api\Request))
#8 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(74): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(84): Omeka\Api\Manager->create('zotero_imports', Array, Array)
#10 /websites/omekadev/home/www/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(71): Omeka\Mvc\Controller\Plugin\Api->create('zotero_imports', Array)
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): ZoteroImport\Controller\IndexController->importAction()
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#19 /websites/omekadev/home/www/omeka-s/index.php(17): Zend\Mvc\Application->run()
#20 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null' in /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#1 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#2 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1018): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#3 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#4 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(249): Doctrine\ORM\EntityManager->flush()
#6 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(215): Omeka\Api\Adapter\AbstractEntityAdapter->create(Object(Omeka\Api\Request))
#7 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(74): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#8 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(84): Omeka\Api\Manager->create('zotero_imports', Array, Array)
#9 /websites/omekadev/home/www/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(71): Omeka\Mvc\Controller\Plugin\Api->create('zotero_imports', Array)
#10 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): ZoteroImport\Controller\IndexController->importAction()
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#14 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#18 /websites/omekadev/home/www/omeka-s/index.php(17): Zend\Mvc\Application->run()
#19 {main}

Next exception 'Doctrine\DBAL\Exception\NotNullConstraintViolationException' with message 'An exception occurred while executing 'INSERT INTO zotero_import (name, url, version, job_id, undo_job_id) VALUES (?, ?, ?, ?, ?)' with params [null, null, "1937", null, null]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null' in /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(178): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO zot...', Array)
#2 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(281): Doctrine\DBAL\Statement->execute()
#3 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1018): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(249): Doctrine\ORM\EntityManager->flush()
#7 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(215): Omeka\Api\Adapter\AbstractEntityAdapter->create(Object(Omeka\Api\Request))
#8 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(74): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(84): Omeka\Api\Manager->create('zotero_imports', Array, Array)
#10 /websites/omekadev/home/www/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(71): Omeka\Mvc\Controller\Plugin\Api->create('zotero_imports', Array)
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): ZoteroImport\Controller\IndexController->importAction()
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#19 /websites/omekadev/home/www/omeka-s/index.php(17): Zend\Mvc\Application->run()
#20 {main}
```

**Comment by jimsafley** [comment]
Sorry, I forgot to mention that you'll need to reinstall the module.

**Comment by kimisgold** [comment]
Pulled and reinstalled, got the following error using user id 15:

```
exception 'ErrorException' with message 'stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed' in /Users/kim/Sites/omeka-s/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php:281
Stack trace:
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'stream_socket_e...', '/Users/kim/Site...', 281, Array)
#1 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php(281): stream_socket_enable_crypto(Resource id #745, true, 57)
#2 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-http/src/Client.php(1370): Zend\Http\Client\Adapter\Socket->connect('api.zotero.org', 443, true)
#3 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-http/src/Client.php(893): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '')
#4 /Users/kim/Sites/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(197): Zend\Http\Client->send()
#5 /Users/kim/Sites/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(64): ZoteroImport\Controller\IndexController->sendApiRequest(Array)
#6 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): ZoteroImport\Controller\IndexController->importAction()
#7 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#14 /Users/kim/Sites/omeka-s/index.php(17): Zend\Mvc\Application->run()
#15 {main}

Next exception 'Zend\Http\Client\Adapter\Exception\RuntimeException' with message 'Unable to enable crypto on TCP connection api.zotero.org: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.' in /Users/kim/Sites/omeka-s/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php:308
Stack trace:
#0 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-http/src/Client.php(1370): Zend\Http\Client\Adapter\Socket->connect('api.zotero.org', 443, true)
#1 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-http/src/Client.php(893): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '')
#2 /Users/kim/Sites/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(197): Zend\Http\Client->send()
#3 /Users/kim/Sites/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(64): ZoteroImport\Controller\IndexController->sendApiRequest(Array)
#4 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): ZoteroImport\Controller\IndexController->importAction()
#5 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /Users/kim/Sites/omeka-s/index.php(17): Zend\Mvc\Application->run()
#13 {main}
```

**Comment by jimsafley** [comment]
You need to configure Omeka's HTTP client in config/local.config.php by setting `sslcapath` or `sslcafile` to whatever is pertinent to your environment. For Ubuntu `sslcapath` is /etc/ssl/certs

**Comment by jimsafley** [comment]
Alternatively, you could just switch to the cURL adapter by adding the following line to the `http_client` config:

```
'adapter'   => 'Zend\Http\Client\Adapter\Curl',
```

**Comment by kimisgold** [comment]
Thank you: switching to the cURL adapter fixed it for me.

**Comment by jimsafley** [comment]
I made more changes that will require you to reinstall the module. Also, I want to confirm that you've been testing every import option, including importing groups, collections, files, and by timestamp. All of these need to be tested in order for this issue to be closed and the module to be ready for release.

**Comment by mebrett** [comment]
The only thing I haven't tried yet is by timestamp. I'll take a look, and we can also get @alyssafahringer to try again on Monday, when she is in.

**Comment by alyssafahringer** [comment]
Tested on both dev and Megan's installs. Worked on both, and was able to import files, and import after date.
